// Optional browser smoke suite: requires the chrome-devtools CLI and a Vite server.
// Usage: node tests/browser-smoke.cjs [http://127.0.0.1:5174/] [pageId]
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const globalRoot = execFileSync('npm.cmd', ['root', '-g'], { encoding: 'utf8', shell: true }).trim();
const pkg = JSON.parse(fs.readFileSync(path.join(globalRoot, 'chrome-devtools-mcp/package.json'), 'utf8'));
const cli = path.join(globalRoot, 'chrome-devtools-mcp', pkg.bin['chrome-devtools']);
const pageId = process.argv[3] || '1';
const run = args => execFileSync(process.execPath, [cli, ...args], { encoding: 'utf8', timeout: 60000 });
console.log(run(['navigate_page', pageId, '--url', process.argv[2] || 'http://127.0.0.1:5174/', '--initScript', fs.readFileSync(path.join(__dirname, 'fixtures/browser.js'), 'utf8')]));
const smoke = async () => {
  if (!window.__test) throw Error('Refusing to test without in-memory API fixtures');
  const passed = [];
  const pause = () => new Promise(resolve => setTimeout(resolve, 40));
  const wait = async (condition, message) => { for(let i=0;i<100;i++){if(condition())return;await pause();}throw Error('Timeout: '+message); };
  const assert = (condition,message) => {if(!condition)throw Error(message);};
  const button = (text, root=document) => [...root.querySelectorAll('button')].find(b=>b.textContent.trim()===text);
  const click = async element => {assert(element,'Missing button after ' + passed.join(', ') + '\n' + new Error().stack); assert(!element.disabled,'Button is disabled: '+element.textContent);element.click();await pause();};
  const nav = async name => {await click([...document.querySelectorAll('.sidebar .nav')].find(b=>b.textContent.includes(name)));};
  const fill = async (selector,value) => {const el=document.querySelector(selector);assert(el,'Missing field '+selector);const prototype=el.tagName==='SELECT'?HTMLSelectElement.prototype:el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));await pause();};
  const openModal = () => document.querySelector('.modal-layer.open');
  const save = async () => {await click(openModal().querySelector('button[type=submit]'));await wait(()=>!openModal(),'modal saved');};
  await wait(()=>document.querySelector('.session-card'),'schedule loaded');
  assert(button('Copy week forward'),'Copy-week control missing');
  passed.push('preprod schedule and copy-week control');
  const { apiClient } = await import('/src/services/apiClient.js');
  const fetchFixture = window.fetch;
  window.fetch = async (...args) => { await new Promise(resolve => setTimeout(resolve, 350)); return fetchFixture(...args); };
  const loadingRequest = apiClient.get('Students');
  await wait(() => document.querySelector('.loading-screen')?.open, 'loading screen visible');
  await loadingRequest;
  await wait(() => !document.querySelector('.loading-screen')?.open, 'loading screen closed');
  window.__test.failNext = 'Students';
  const failedRequest = apiClient.get('Students').catch(error => error);
  await wait(() => document.querySelector('.loading-screen')?.open, 'loading screen before failure');
  await failedRequest;
  await wait(() => !document.querySelector('.loading-screen')?.open, 'loading screen closed after failure');
  window.fetch = fetchFixture;
  passed.push('loading screen during service calls and cleanup on failure');
  const completions = [];
  window.fetch = () => new Promise(resolve => completions.push(resolve));
  const firstBatch = Promise.all([apiClient.get('Students'), apiClient.get('Tutors')]);
  await wait(() => document.querySelector('.loading-screen').open, 'loading for overlapping calls');
  completions[0](new Response('[]'));
  await new Promise(resolve => setTimeout(resolve, 250));
  assert(document.querySelector('.loading-screen').open, 'Loading closed before the last request');
  completions[1](new Response('[]'));
  await firstBatch;
  await pause();
  const followUp = apiClient.get('Students');
  await new Promise(resolve => setTimeout(resolve, 250));
  assert(document.querySelector('.loading-screen').open, 'Loading closed during a follow-up request');
  completions[2](new Response('[]'));
  await followUp;
  await wait(() => !document.querySelector('.loading-screen').open, 'loading closes after all requests');
  window.fetch = fetchFixture;
  passed.push('loading stays open until all concurrent and follow-up requests finish');


  assert(!document.querySelector('.session-card').draggable,'Schedule card is draggable');

  await nav('All sessions');await wait(()=>document.querySelector('.data-table tbody')?.textContent.includes('Test Student'),'all sessions loaded');
  await click(document.querySelector('#date-range-filter-btn'));
  assert(button('This week')&&button('This month'),'Current-date presets missing');
  await fill('#date-input-from',window.__test.dateAt(3));await fill('#date-input-to',window.__test.dateAt(2));
  assert([...document.querySelectorAll('.date-picker-popover button')].find(b=>b.textContent.includes('Apply')).disabled,'Reversed range allowed');
  await fill('#date-input-from',window.__test.dateAt(2));
  await click([...document.querySelectorAll('.date-picker-popover button')].find(b=>b.textContent.includes('Apply')));
  await wait(()=>window.__test.requests.some(r=>r.path==='Sessions'&&r.query.includes('startDate='+window.__test.dateAt(2))),'date query');
  await click(document.querySelector('[aria-label="Clear date filter"]'));
  await wait(()=>window.__test.requests.at(-1).path==='Sessions'&&window.__test.requests.at(-1).query==='','clear date query');
  passed.push('date filter validates and queries backend; clear resets');

  await wait(()=>button('Attended',document.querySelector('tbody')),'session row restored after clearing filter');
  window.__test.failNext='Sessions/3/status';await click(button('Attended',document.querySelector('tbody')));
  await wait(()=>document.querySelector('[role=alert]')?.textContent.includes('Test server unavailable'),'status failure shown');
  assert(window.__test.sessions()[0].status==='booked','Failed status falsely saved');
  await click(button('Dismiss'));await click(button('Attended',document.querySelector('tbody')));
  await wait(()=>window.__test.sessions()[0].status==='attended','status saved');
  passed.push('status PATCH failure and retry');

  await nav('Students');await wait(()=>button('Edit record'),'student directory');
  await wait(()=>document.querySelector('.history')?.textContent.includes('Physics'),'student history');
  await click(button('Edit record'));await wait(()=>openModal()?.querySelector('#f_name')?.value==='Test Student'&&!openModal()?.querySelector('button[type=submit]').disabled,'profile loaded');
  assert(!document.querySelector('#f_school')&&!document.querySelector('#f_year'),'Unsupported student fields still present');
  await fill('#student-notes','Updated notes');
  await fill('#student-mediaConsent','');
  await fill('#student-firstAidNeeded','true');
  await fill('#student-availabilityNotes','Friday after school');
  await click(button('Make primary',openModal().querySelectorAll('.guardian-fields')[1]));
  assert(document.querySelector('#guardian-0-guardianName').value==='Second Guardian','Promotion did not move guardian to first row');await click(document.querySelector('#student_subjects_btn'));
  await click([...document.querySelectorAll('.subject-option-item')].find(b=>b.textContent.includes('Year 12')));
  window.__test.failNext='Students/7';await click(openModal().querySelector('button[type=submit]'));
  await wait(()=>openModal()?.textContent.includes('Test server unavailable'),'student save error');
  assert(window.__test.students()[0].notes.includes('Test School'),'Failed student edit falsely saved');
  await save();
  const updated=window.__test.students()[0];
  assert(updated.guardians.length===2&&updated.mediaConsent===null&&updated.firstAidNeeded===true,'Student edit lost profile fields');
  assert(updated.subjects.length===2&&updated.subjects[1].subjectId===43,'Subject IDs not preserved');
  assert(updated.notes==='Updated notes'&&updated.availabilityNotes==='Friday after school','Notes not saved');
  assert(updated.guardians[0].guardianId===12&&updated.guardians[0].isPrimary===true&&updated.guardians[1].isPrimary===false,'First guardian not primary');
  passed.push('student edit, failure retry, secondary guardian and consent preservation, distinct subject IDs');

  await click([...document.querySelectorAll('#page-students button')].find(b=>b.textContent.includes('Add student')));
  await fill('#f_name','New Test Student');await fill('#guardian-0-guardianName','New Guardian');await fill('#guardian-0-guardianPhone','0400000003');await fill('#guardian-0-relationship','Parent');
  assert(button('Remove',openModal().querySelector('.guardian-fields')).disabled,'Last guardian can be removed');
  await click(button('Add guardian',openModal()));
  await fill('#guardian-1-guardianName','Another Guardian');await fill('#guardian-1-guardianPhone','0400000004');await fill('#guardian-1-relationship','Aunt');
  await click(document.querySelector('#student_subjects_btn'));await click([...document.querySelectorAll('.subject-option-item')].find(b=>b.textContent.includes('Year 12')));await save();
  await wait(()=>window.__test.students().length===2,'student created');
  await wait(()=>document.querySelector('.detail-hero h2')?.textContent==='New Test Student','new student selected');
  await click(button('Edit record'));await wait(()=>!openModal()?.querySelector('button[type=submit]').disabled,'new profile loaded');
  await click(button('Remove',openModal().querySelector('.guardian-fields')));
  assert(document.querySelector('#guardian-0-guardianName').value==='Another Guardian','Removing primary did not promote next guardian');
  await fill('#f_active','false');await save();
  assert(window.__test.students()[1].guardians.length===1&&window.__test.students()[1].guardians[0].isPrimary,'Remaining guardian not primary');
  assert(window.__test.students()[1].isActive===false,'Deactivation not saved');
  passed.push('student creation, guardian removal/promotion and deactivation');

  await nav('Tutors');await wait(()=>document.querySelector('.tutor-grid')?.textContent.includes('Test Tutor'),'tutors loaded');
  await click([...document.querySelectorAll('.tutor-grid button')].find(b=>b.textContent.includes('Edit')));
  await click(document.querySelector('#tutor_subjects_btn'));
  await click([...document.querySelectorAll('.subject-option-item')].find(b=>b.textContent.includes('Year 11')));
  await save();
  assert(window.__test.requests.some(r=>r.path==='Tutors/9'&&r.method==='PUT'&&r.body.subjectIds.length===1&&r.body.subjectIds[0]===43),'Tutor subject selection did not use correct ID');
  passed.push('tutor selector saves exact subject IDs');
  await nav('Weekly schedule');
  await click([...document.querySelectorAll('#page-schedule button')].find(b=>b.textContent.includes('New session')));
  await wait(()=>document.querySelector('#f_student option[value="7"]'),'booking students');
  await fill('#f_student','7');await fill('#f_tutor','9');
  await wait(()=>document.querySelector('#f_subject option[value="43"]'),'booking subjects');
  await fill('#f_subject','43');await fill('#f_date',window.__test.dateAt(3));
  await save();
  await wait(()=>window.__test.sessions().length===2,'booking created');
  assert(window.__test.sessions()[1].status==='booked','New booking lost booked status');
  await wait(()=>[...document.querySelectorAll('.session-card')].some(c=>c.textContent.includes('Booked')),'new booking rendered');
  await click([...document.querySelectorAll('.session-card')].find(c=>c.textContent.includes('Booked')).querySelector('button'));
  await wait(()=>button('Edit',openModal())&&!button('Edit',openModal()).disabled,'session details');
  await click(button('Edit',openModal()));await fill('#f_time','16:00');await save();
  assert(window.__test.sessions()[1].startTime==='16:00:00','Session edit failed');
  passed.push('preprod create, details and edit booking flow');
  await click(button('Copy week forward'));await click(button('Confirm copy'));
  await wait(()=>document.querySelector('.copy-result')?.textContent.includes('Week copied successfully'),'copy result');
  assert(window.__test.requests.some(r=>r.path==='Sessions/copy-week-forward'&&r.method==='POST'),'Copy endpoint not called');
  passed.push('preprod copy-week confirmation and result');
  await nav('Availability');
  await wait(()=>document.querySelector('.availability-grid'),'availability grid');
  const addAvailability = () => [...document.querySelectorAll('#page-availability button')].find(b=>b.textContent.includes('Add availability'));
  await click(addAvailability());
  await fill('#f_avail_day','Wednesday');await fill('#f_avail_start','18:00');await fill('#f_avail_end','15:00');
  await click(openModal().querySelector('button[type=submit]'));
  assert(openModal().textContent.includes('End time must be after start time'),'Invalid availability accepted');
  await fill('#f_avail_start','15:00');await fill('#f_avail_end','18:00');await save();
  const removeSlot = () => [...document.querySelectorAll('#page-availability .window button')].find(b=>b.getAttribute('aria-label').includes('Wednesday'));
  await wait(()=>removeSlot(),'new availability displayed');
  assert(window.__test.requests.some(r=>r.path==='Tutors/9/availability'&&r.body.dayOfWeek===3),'Availability payload day mismatch');
  await click(addAvailability());await fill('#f_avail_day','Wednesday');
  await click(openModal().querySelector('button[type=submit]'));
  await wait(()=>openModal()?.textContent.includes('overlaps'),'overlap error');
  await click(button('Cancel',openModal()));
  window.__test.failNext='Tutors/9/availability/2';await click(removeSlot());
  await wait(()=>document.querySelector('#page-availability [role=alert]')?.textContent.includes('Test server unavailable'),'deletion error shown');
  assert(removeSlot(),'Failed deletion removed availability from UI');
  await click(removeSlot());await wait(()=>!removeSlot()&&!document.querySelector('#page-availability [role=status]'),'availability removed');
  assert(document.querySelectorAll('#page-availability .window').length===1,'Deletion removed the wrong slot');
  passed.push('availability add, validation, overlap rejection and delete failure/retry');
  return passed;
};
const output=run(['evaluate_script',smoke.toString(),'--pageId',pageId]);
console.log(output);
if (!output.includes('availability add, validation, overlap rejection and delete failure/retry')) process.exitCode=1;
